import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import AppShell from "./AppShell";
import { Toaster } from "../components/ui/sonner";

import { TRPCReactProvider } from "~/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

import React from "react";

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <ClerkProvider>
            <html lang="en" className={geist.variable}>
                <body
                    className="flex max-w-full"
                    style={{
                        backgroundColor: "var(--ctp-base)",
                        color: "var(--ctp-text)",
                    }}
                >
                    {/* Global Toaster for notifications */}
                    <Toaster position="bottom-right" />
                    <AppShell>
                        <TRPCReactProvider>{children}</TRPCReactProvider>
                    </AppShell>
                </body>
            </html>
        </ClerkProvider>
    );
}
